#!/usr/bin/env python3
"""E87N factory-layout boot helpers. No arbitrary devices or alternate live roots.

Importing this module performs no I/O. Both actions validate the running board,
root mount and all five partitions before accessing either fixed device.
"""
import argparse
import os
from pathlib import Path
import platform
import re
import stat
import struct
import subprocess
import sys
import tempfile


LAYOUT = {
    1: ("u-boot-env", 8192, 1024),
    2: ("factory", 9216, 8192),
    3: ("fip", 17408, 4096),
    4: ("kernel", 21504, 65536),
    5: ("rootfs", 87040, 15181791),
}
ROOT_DEVICE = "/dev/mmcblk0p5"
FACTORY_DEVICE = "/dev/mmcblk0p2"
ALIASES = tuple(f"/soc/ethernet@15100000/mac@{i}" for i in range(2))
NETWORK_BASE = Path("/run/systemd/network/10-netplan-e87n-wired.network")
NETWORK_NAMES = tuple(f"05-e87n-factory-gmac{i}.network" for i in range(2))
NETWORK_HEADER = "# Generated by e87n factory-boot; volatile, do not edit.\n"


def require(ok, message):
    if not ok:
        raise ValueError(message)


def unescape_mount(value):
    return re.sub(r"\\([0-7]{3})", lambda match: chr(int(match[1], 8)), value)


def parse_mountinfo(text):
    result = []
    for line in text.splitlines():
        left, separator, right = line.partition(" - ")
        fields, tail = left.split(), right.split()
        require(separator and len(fields) >= 6 and len(tail) >= 3,
                "invalid mountinfo record")
        result.append({"dev": fields[2], "root": unescape_mount(fields[3]),
                       "mount": unescape_mount(fields[4]), "options": fields[5].split(","),
                       "type": tail[0], "source": unescape_mount(tail[1])})
    return result


def validate_live(snapshot, writable_required=True):
    """Pure check; sector counts are the recorded factory GPT, in 512B units."""
    require(snapshot["machine"] == "aarch64" and snapshot["uid"] == 0,
            "requires native aarch64 root on the running E87N")
    require(snapshot["model"] == b"EdgePi E87N\0" and
            b"edgepi,e87n" in snapshot["compatible"].rstrip(b"\0").split(b"\0"),
            "running device tree is not EdgePi E87N")
    require(snapshot["removable"] == 0 and snapshot["card_type"] == "MMC",
            "mmcblk0 is not non-removable eMMC")
    require(set(snapshot["parts"]) == set(LAYOUT), "need exactly factory partitions p1..p5")
    devices = []
    for number, expected in LAYOUT.items():
        part = snapshot["parts"][number]
        require((part["name"], part["start"], part["size"]) == expected,
                f"mmcblk0p{number} label/start/size differs from factory layout")
        require(part["parent_ok"] and part["number"] == number,
                f"mmcblk0p{number} is not a child of the expected disk")
        require(re.fullmatch(r"\d+:\d+", part["dev"]) is not None, "invalid device identity")
        devices.append(part["dev"])
    require(len(set(devices)) == 5, "duplicate partition device identities")
    require(snapshot["sectors"] >= LAYOUT[5][1] + LAYOUT[5][2] + 33,
            "disk is too small for factory partitions and backup GPT")
    roots = [entry for entry in snapshot["mounts"] if entry["mount"] == "/"]
    require(len(roots) == 1, "ambiguous running root mount")
    root = roots[0]
    require(root["root"] == "/" and root["type"] == "ext4" and
            root["source"] == ROOT_DEVICE and root["dev"] == devices[4] and
            (not writable_required or "rw" in root["options"]),
            "running root must be ext4 on mmcblk0p5 (writable for resize)")


def live_snapshot():
    base = Path("/sys/class/block")
    disk = (base / "mmcblk0").resolve(strict=True)
    names = {path.name for path in base.iterdir() if path.name.startswith("mmcblk0p")}
    require(names == {f"mmcblk0p{i}" for i in LAYOUT}, "unexpected eMMC partition set")
    parts = {}
    for number in LAYOUT:
        path = base / f"mmcblk0p{number}"
        fields = dict(line.split("=", 1) for line in (path / "uevent").read_text().splitlines()
                      if "=" in line)
        parts[number] = {"name": fields.get("PARTNAME"),
                         "start": int((path / "start").read_text()),
                         "size": int((path / "size").read_text()),
                         "number": int((path / "partition").read_text()),
                         "dev": (path / "dev").read_text().strip(),
                         "parent_ok": path.resolve(strict=True).parent == disk}
    dt = Path("/sys/firmware/devicetree/base")
    return {"machine": platform.machine(), "uid": os.geteuid(),
            "model": (dt / "model").read_bytes(), "compatible": (dt / "compatible").read_bytes(),
            "removable": int((disk / "removable").read_text()),
            "card_type": (disk / "device/type").read_text().strip(),
            "sectors": int((disk / "size").read_text()), "parts": parts,
            "mounts": parse_mountinfo(Path("/proc/self/mountinfo").read_text())}


def open_partition(number, snapshot):
    require(number in (2, 5), "only factory reads and rootfs access are supported")
    path = FACTORY_DEVICE if number == 2 else ROOT_DEVICE
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        identity = f"{os.major(info.st_rdev)}:{os.minor(info.st_rdev)}"
        require(stat.S_ISBLK(info.st_mode) and identity == snapshot["parts"][number]["dev"],
                f"{path} is not the verified partition device")
    except BaseException:
        os.close(fd)
        raise
    return fd


def ext4_geometry(superblock):
    require(len(superblock) == 1024 and superblock[56:58] == b"\x53\xef",
            "root partition lacks a complete ext4 superblock")
    require(struct.unpack_from("<I", superblock, 24)[0] == 2,
            "factory rootfs requires the audited 4096-byte ext4 block size")
    blocks = struct.unpack_from("<I", superblock, 4)[0]
    if struct.unpack_from("<I", superblock, 96)[0] & 0x80:
        blocks |= struct.unpack_from("<I", superblock, 336)[0] << 32
    maximum = LAYOUT[5][2] * 512 // 4096
    require(0 < blocks <= maximum, "ext4 geometry exceeds the fixed rootfs partition")
    return blocks, maximum


def resize_rootfs():
    snapshot = live_snapshot()
    validate_live(snapshot)
    fd = open_partition(5, snapshot)
    try:
        blocks, maximum = ext4_geometry(os.pread(fd, 1024, 1024))
        if blocks == maximum:
            print("OK: factory rootfs already fills mmcblk0p5; no resize needed")
            return
        # Recheck immediately before the sole write-capable command. No GPT tool,
        # partition editor, reboot, boot environment operation or device option.
        current = live_snapshot()
        validate_live(current)
        require(current["parts"] == snapshot["parts"], "layout changed during validation")
        check_fd = open_partition(5, current)
        os.close(check_fd)
        subprocess.run(["/usr/sbin/resize2fs", ROOT_DEVICE], check=True, timeout=90)
        actual, maximum = ext4_geometry(os.pread(fd, 1024, 1024))
        require(actual == maximum, "resize2fs returned without filling the fixed partition")
        print("OK: resized ext4 inside mmcblk0p5; partition table untouched")
    finally:
        os.close(fd)


def factory_macs(data):
    require(len(data) == 12, "short factory MAC read at offsets 0x24/0x2a")
    addresses = (data[:6], data[6:])
    for value in addresses:
        require(value != b"\0" * 6 and value != b"\xff" * 6 and not value[0] & 1,
                "factory contains an invalid zero/broadcast/multicast MAC")
    require(addresses[0] != addresses[1], "factory GMAC addresses are identical")
    return tuple(":".join(f"{byte:02x}" for byte in value) for value in addresses)


def port_networks(base, addresses):
    """Keep netplan's generated DHCP settings, adding per-DT-port MAC selection."""
    require(len(addresses) == 2, "need two factory MACs")
    # Reject unfamiliar Match logic instead of widening its scope. Repeated
    # address/route sections elsewhere are retained verbatim, not reserialized.
    lines = base.splitlines(keepends=True)
    sections = [line.strip() for line in lines if line.strip().startswith("[")]
    require(sections.count("[Match]") == 1 and sections.count("[Network]") == 1,
            "unexpected generated netplan structure")
    section, names, dhcp = "", [], []
    for line in lines:
        value = line.strip()
        if not value or value.startswith(("#", ";")):
            continue
        require(not value.endswith("\\"), "continued netplan directives are unsupported")
        if value.startswith("["):
            section = value
            continue
        key, equal, setting = value.partition("=")
        require(equal, "invalid netplan directive")
        if section == "[Match]":
            require(key == "Name" and setting == "e*", "netplan wired Match is no longer Name=e*")
            names.append(setting)
        if section == "[Link]":
            require(key != "MACAddress", "netplan already specifies a MAC override")
        if section == "[Network]" and key == "DHCP":
            dhcp.append(setting)
    require(names == ["e*"] and dhcp == ["yes"], "expected existing dual-stack netplan DHCP")
    outputs = []
    for index, address in enumerate(addresses):
        require(re.fullmatch(r"(?:[0-9a-f]{2}:){5}[0-9a-f]{2}", address), "invalid MAC format")
        result, section = [], ""
        for line in lines:
            if line.strip().startswith("["):
                section = line.strip()
            if section == "[Match]" and line.strip().startswith("Name="):
                # net.ifnames=0 keeps ethN names, but enumeration is not used
                # to infer port identity. v257 udev derives endN from DT aliases.
                result.append(f"Name=e*\nProperty=ID_NET_NAME_ONBOARD=end{index}\n")
            else:
                result.append(line)
        outputs.append(NETWORK_HEADER + "".join(result).rstrip() +
                       f"\n\n[Link]\nMACAddress={address}\n")
    return tuple(outputs)


def managed_network_file(path):
    if os.path.lexists(path):
        require(path.is_file() and not path.is_symlink() and
                path.read_text().startswith(NETWORK_HEADER),
                f"refusing unrelated runtime network file: {path}")


def validate_interfaces(interfaces):
    require(set(interfaces) == {"eth0", "eth1"}, "expected both eth0 and eth1 before DHCP")
    for index in range(2):
        node, flags = interfaces[f"eth{index}"]
        require(node == ALIASES[index], f"eth{index} does not map to its GMAC DT alias")
        require(not flags & 1, f"eth{index} is already administratively up; refusing live reconfiguration")


def setup_macs():
    snapshot = live_snapshot()
    validate_live(snapshot, writable_required=False)
    dt = Path("/sys/firmware/devicetree/base")
    for index, expected in enumerate(ALIASES):
        require((dt / "aliases" / f"ethernet{index}").read_bytes() == expected.encode() + b"\0",
                f"missing/wrong ethernet{index} GMAC alias")
    interfaces = {}
    for index in range(2):
        interface = Path(f"/sys/class/net/eth{index}")
        node = (interface / "of_node").resolve(strict=True)
        interfaces[f"eth{index}"] = ("/" + str(node.relative_to(dt)),
                                      int((interface / "flags").read_text().strip(), 16))
    validate_interfaces(interfaces)
    require(NETWORK_BASE.is_file() and not NETWORK_BASE.is_symlink(),
            "netplan wired DHCP configuration has not been generated")
    # Don't silently bypass drop-ins to the original network file.
    for prefix in ("/etc", "/run", "/usr/lib", "/usr/local/lib"):
        dropin = Path(prefix) / "systemd/network" / (NETWORK_BASE.name + ".d")
        require(not dropin.exists(), "netplan network drop-ins require explicit factory-MAC integration")
    fd = open_partition(2, snapshot)
    try:
        addresses = factory_macs(os.pread(fd, 12, 0x24))
    finally:
        os.close(fd)
    configs = port_networks(NETWORK_BASE.read_text(), addresses)
    directory = NETWORK_BASE.parent
    require(directory.resolve() == directory, "runtime network directory is redirected")
    paths = [directory / name for name in NETWORK_NAMES]
    for path in paths:
        managed_network_file(path)
    try:
        for index, address in enumerate(addresses):
            subprocess.run(["/usr/sbin/ip", "link", "set", "dev", f"eth{index}",
                            "address", address], check=True, timeout=3)
        for path, contents in zip(paths, configs):
            fd, temporary = tempfile.mkstemp(prefix=".e87n-factory-", dir=directory)
            try:
                with os.fdopen(fd, "w") as output:
                    output.write(contents)
                    output.flush()
                    os.fchmod(output.fileno(), 0o644)
                    os.fsync(output.fileno())
                os.replace(temporary, path)
            finally:
                if os.path.exists(temporary):
                    os.unlink(temporary)
    except BaseException:
        for path in paths:
            managed_network_file(path)
            if path.exists():
                path.unlink()
        raise
    print("OK: factory GMAC0/1 policies prepared before networkd; netplan DHCP retained")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("resize", "mac"))
    args = parser.parse_args()
    try:
        (resize_rootfs if args.action == "resize" else setup_macs)()
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as error:
        print(f"ERROR: E87N factory {args.action}: {error}", file=sys.stderr)
        if args.action == "mac":
            print("ERROR: factory MAC policy unavailable; networkd may use its existing DHCP/MAC fallback",
                  file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
