#!/bin/sh
export PATH=/usr/sbin:/usr/bin:/sbin:/bin LC_ALL=C PYTHONDONTWRITEBYTECODE=1
umask 077
[ "$$" = 1 ] || exit 1
fail() { echo "RAMDIAG FAIL: $*" >&2; while :; do sleep 60; done; }
[ ! -e /sys/class/block/mmcblk0 ] || fail 'eMMC appeared'
mkdir -p /run/ssh /run/sshd
chmod 0755 /run/sshd
echo 'RAMDIAG STAGE generating ephemeral SSH host key'
ssh-keygen -q -t ed25519 -N '' -f /run/ssh/ssh_host_ed25519_key || fail hostkey
/usr/sbin/sshd -t -f /etc/ssh/sshd_config || fail sshd-config
echo 'RAMDIAG SSH READY: root password is doumao'
while :; do
    [ ! -e /sys/class/block/mmcblk0 ] || fail 'eMMC appeared after SSH start'
    /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config >>/run/ramdiag/sshd.log 2>&1 &
    pid=$!
    while kill -0 "$pid" 2>/dev/null; do
        [ ! -e /sys/class/block/mmcblk0 ] || fail 'eMMC appeared while SSH was running'
        sleep 2
    done
    echo 'RAMDIAG SSH exited; retrying in 5 seconds' >&2
    sleep 5
done
