#!/bin/sh
set -eu

PREREQ=""

prereqs() {

    printf '%s\n' "$PREREQ"
}

case "${1:-}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

for firmware in \
    /usr/lib/firmware/mediatek/mt7987/i2p5ge-phy-pmb.bin \
    /usr/lib/firmware/mediatek/mt7987/i2p5ge-phy-DSPBitTb.bin; do
    [ -f "$firmware" ] || exit 1
    install -D -m 0644 "$firmware" "${DESTDIR}${firmware}"
done
