#!/usr/bin/env bash
# Build the architecture-independent userspace package without installing it.
set -Eeuo pipefail
export LC_ALL=C
export SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-0}
umask 022

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
packaging_dir="$repo_dir/packaging/e87n-display"
output_dir=
version=
version_given=false

usage() {
	printf 'Usage: %s --output-dir PATH [--version VERSION]\n' "${0##*/}"
	printf 'Default version: packaging/e87n-display/VERSION; requires dpkg and dpkg-deb.\n'
}
fail() { printf 'e87n-display: %s\n' "$*" >&2; exit 2; }

while (( $# )); do
	case "$1" in
		--output-dir)
			(( $# >= 2 )) && [[ -n "$2" && "$2" != --* ]] || fail '--output-dir needs a path'
			[[ -z "$output_dir" ]] || fail 'duplicate --output-dir'
			output_dir=$2; shift 2 ;;
		--version)
			(( $# >= 2 )) && [[ -n "$2" && "$2" != --* ]] || fail '--version needs a value'
			[[ "$version_given" == false ]] || fail 'duplicate --version'
			version=$2; version_given=true; shift 2 ;;
		-h|--help) usage; exit 0 ;;
		*) fail "unknown argument: $1" ;;
	esac
done
[[ -n "$output_dir" ]] || fail '--output-dir is required'
if [[ "$version_given" == false ]]; then
	[[ -f "$packaging_dir/VERSION" ]] || fail 'missing packaging/e87n-display/VERSION'
	version=$(< "$packaging_dir/VERSION")
fi
# Reject paths, control characters and control-file injection before invoking dpkg.
[[ "$version" =~ ^[0-9][0-9A-Za-z.+:~\-]*$ ]] || fail 'invalid Debian version'
for tool in dpkg dpkg-deb md5sum; do
	command -v "$tool" >/dev/null 2>&1 || fail "required build tool not found: $tool (build on Debian/Linux)"
done
dpkg --validate-version "$version" || fail "invalid Debian version: $version"

# Resolve once; all generated files stay in a unique staging directory. A failed
# build leaves an existing same-version artifact intact.
mkdir -p -- "$output_dir"
output_dir=$(cd "$output_dir" && pwd)
artifact="$output_dir/e87n-display_${version}_all.deb"
[[ ! -L "$artifact" && ! -d "$artifact" ]] || fail "output is a symlink or directory: $artifact"
stage_dir=$(mktemp -d "$output_dir/.e87n-display.XXXXXXXX")
trap 'rm -rf -- "$stage_dir"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
package_root="$stage_dir/package"
python_dir="$package_root/usr/lib/python3/dist-packages/e87n"
doc_dir="$package_root/usr/share/doc/e87n-display"
install -d -m 0755 "$package_root/DEBIAN" "$python_dir" "$doc_dir" \
	"$package_root/usr/bin" "$package_root/usr/lib/systemd/system" \
	"$package_root/etc/e87n" "$package_root/etc/modules-load.d"

# Explicit whitelist: provisioning, image defaults, unrelated future modules
# and host-generated bytecode must never become package payload implicitly.
for source in __init__.py __main__.py hardware.py display.py doctor.py; do
	[[ -f "$repo_dir/board-support/e87n/$source" ]] || fail "missing Python source: $source"
	install -m 0644 "$repo_dir/board-support/e87n/$source" "$python_dir/$source"
done
install -m 0755 "$repo_dir/board-support/e87nctl" "$package_root/usr/bin/e87nctl"
install -m 0644 "$repo_dir/board-support/display.json" "$package_root/etc/e87n/display.json"
install -m 0644 "$repo_dir/board-support/e87n-display.conf" "$package_root/etc/modules-load.d/e87n-display.conf"
install -m 0644 "$repo_dir/board-support/systemd/e87n-display.service" "$package_root/usr/lib/systemd/system/e87n-display.service"
install -m 0644 "$packaging_dir/copyright" "$packaging_dir/README.Debian" "$doc_dir/"

sed "s/@VERSION@/$version/" "$packaging_dir/control" > "$package_root/DEBIAN/control"
printf 'Installed-Size: %s\n' "$(du -sk "$package_root" | awk '{print $1}')" >> "$package_root/DEBIAN/control"
install -m 0644 "$packaging_dir/conffiles" "$package_root/DEBIAN/conffiles"
for script in postinst prerm postrm; do
	install -m 0755 "$packaging_dir/$script" "$package_root/DEBIAN/$script"
done
(
	cd "$package_root"
	find etc usr -type f -print0 | LC_ALL=C sort -z | xargs -0 md5sum > DEBIAN/md5sums
)
dpkg-deb --root-owner-group -Zxz --build "$package_root" "$stage_dir/${artifact##*/}"
mv -f -- "$stage_dir/${artifact##*/}" "$artifact"
printf 'Built %s\n' "$artifact"
